const en = {
  workspace:'Creator workspace', heading:'An idea. A story. Your reel.', newProject:'New project', projects:'Your projects', chooseProject:'Open a saved project', importPlan:'Import plan', exportPlan:'Export plan', deleteProject:'Delete project', deleteConfirm:'Delete this saved project? Media files will be kept.',
  idea:'Your video idea', placeholder:'Describe the story, your audience and your message…', language:'Video language', duration:'Length', style:'Style', format:'Format', generate:'Generate with AI', demoPlan:'Create demo plan', seconds:'sec', vertical:'Vertical', landscape:'Landscape', script:'Script', scenes:'Scenes', voice:'Voice', captions:'Subtitles', video:'MP4', images:'Images', empty:'Start with your idea', emptyText:'Plan your story, add images and a voice, then download your video.', demoHelp:'Use demo cards or upload your own images and audio without API keys.',
  saved:'Saved', saving:'Saving…', localDraft:'Local draft', retrySave:'Retry save', connection:'Connection', connected:'Server connected', offline:'Server offline', check:'Check connection', aiReady:'AI script & images ready', aiDemo:'Demo mode · no AI key', voiceReady:'ElevenLabs connected', voiceMissing:'ElevenLabs not configured', renderReady:'MP4 export ready', renderMissing:'FFmpeg is missing',
  demoDraft:'Demo draft', aiDraft:'AI draft', manualDraft:'Your draft', name:'Project name', scriptLabel:'Voiceover script', generateVoice:'Generate voice', uploadAudio:'Upload audio', voiceId:'ElevenLabs voice ID', loadVoices:'Load my voices', voiceDefault:'Default voice', narration:'Narration', downloadAudio:'Download audio', removeAudio:'Remove audio', voiceHelp:'Upload audio, or configure ElevenLabs in the server settings.', audioFormats:'MP3, WAV, M4A, OGG, FLAC or WebM · 20 MB · up to 3 minutes',
  makeImages:'Generate images', demoImages:'Create demo cards', imageHelp:'Add one image per scene. The export adds a slow camera move.', prompt:'Visual prompt', screenText:'On-screen text', sceneTitle:'Scene title', uploadImage:'Upload image', yourImage:'Your image', aiImage:'AI image', demoCard:'Demo card', export:'Export video', quality:'Video quality', preview:'720p · Preview', fullHD:'1080p · Full HD', burn:'Burn subtitles into the video', importSrt:'Import SRT', downloadSrt:'Download SRT', removeSrt:'Remove imported subtitles', srtHelp:'ElevenLabs provides timed subtitles. You can also upload an SRT file.', noAudio:'This export has no narration.', demoNotice:'This export includes clearly labelled demo cards.', render:'Render MP4', downloadVideo:'Download MP4', needImages:'Add an image to every scene to export.', optional:'optional', retry:'Retry', planOnly:'JSON contains your script and scene plan; media files stay on this server.',
  creatingPlan:'Creating your plan', generatingVoice:'Creating narration', uploading:'Uploading', rendering:'Rendering video', imageJob:'Preparing images', resume:'Resume job', settings:'Setup guide', setupHelp:'Copy .env.example to .env on the server, add your OpenAI and ElevenLabs API keys, then restart. Keys are never sent to this browser.', ready:'Ready', savedHelp:'Projects save automatically on this server. The browser also keeps your latest draft.',
};
const ar = {
  workspace:'مساحة صناعة الفيديو', heading:'فكرة. حكاية. فيديو من صنعك.', newProject:'مشروع جديد', projects:'مشاريعك', chooseProject:'افتح مشروعًا محفوظًا', importPlan:'استيراد مشروع', exportPlan:'تنزيل خطة المشروع', deleteProject:'حذف المشروع', deleteConfirm:'هل تريد حذف المشروع المحفوظ؟ ستبقى ملفات الوسائط.',
  idea:'فكرة الفيديو', placeholder:'صف القصة والجمهور والرسالة التي تريد إيصالها…', language:'لغة الفيديو', duration:'المدة', style:'الأسلوب', format:'المقاس', generate:'توليد بالذكاء الاصطناعي', demoPlan:'إنشاء خطة تجريبية', seconds:'ث', vertical:'طولي', landscape:'أفقي', script:'النص', scenes:'المشاهد', voice:'الصوت', captions:'الترجمة', video:'MP4', images:'الصور', empty:'ابدأ بفكرتك', emptyText:'رتّب القصة، وأضف الصور والصوت، ثم نزّل الفيديو.', demoHelp:'يمكنك تجربة بطاقات توضيحية أو رفع صورك وصوتك بدون مفاتيح API.',
  saved:'تم الحفظ', saving:'جارٍ الحفظ…', localDraft:'مسودة محلية', retrySave:'إعادة محاولة الحفظ', connection:'حالة الاتصال', connected:'السيرفر متصل', offline:'السيرفر غير متصل', check:'فحص الاتصال', aiReady:'توليد النص والصور جاهز', aiDemo:'وضع تجريبي · بدون مفتاح AI', voiceReady:'ElevenLabs متصل', voiceMissing:'ElevenLabs غير مربوط', renderReady:'تصدير MP4 جاهز', renderMissing:'FFmpeg غير مثبت',
  demoDraft:'مسودة تجريبية', aiDraft:'مسودة بالذكاء الاصطناعي', manualDraft:'مسودتك', name:'اسم المشروع', scriptLabel:'نص التعليق الصوتي', generateVoice:'توليد الصوت', uploadAudio:'رفع صوت', voiceId:'معرّف صوت ElevenLabs', loadVoices:'تحميل أصواتي', voiceDefault:'الصوت الافتراضي', narration:'التعليق الصوتي', downloadAudio:'تنزيل الصوت', removeAudio:'إزالة الصوت', voiceHelp:'ارفع تسجيلًا صوتيًا، أو اربط ElevenLabs في إعدادات السيرفر.', audioFormats:'MP3، WAV، M4A، OGG، FLAC أو WebM · حتى 20 MB و3 دقائق',
  makeImages:'توليد الصور', demoImages:'إنشاء بطاقات تجريبية', imageHelp:'أضف صورة لكل مشهد. يضيف التصدير حركة كاميرا بطيئة.', prompt:'وصف الصورة', screenText:'النص الظاهر على الشاشة', sceneTitle:'عنوان المشهد', uploadImage:'رفع صورة', yourImage:'صورتك', aiImage:'صورة مولّدة', demoCard:'بطاقة تجريبية', export:'تصدير الفيديو', quality:'جودة الفيديو', preview:'720p · معاينة', fullHD:'1080p · جودة عالية', burn:'دمج الترجمة داخل الفيديو', importSrt:'رفع ترجمة SRT', downloadSrt:'تنزيل SRT', removeSrt:'إزالة الترجمة المرفوعة', srtHelp:'يوفّر ElevenLabs ترجمة متزامنة مع الصوت. يمكنك أيضًا رفع ملف SRT.', noAudio:'هذا التصدير بدون تعليق صوتي.', demoNotice:'يحتوي هذا التصدير على بطاقات تجريبية واضحة.', render:'تصدير MP4', downloadVideo:'تنزيل MP4', needImages:'أضف صورة لكل مشهد لتفعيل التصدير.', optional:'اختياري', retry:'إعادة المحاولة', planOnly:'ملف JSON يحتوي على النص وخطة المشاهد. تبقى الوسائط على السيرفر.',
  creatingPlan:'جارٍ إعداد الخطة', generatingVoice:'جارٍ توليد الصوت', uploading:'جارٍ الرفع', rendering:'جارٍ تصدير الفيديو', imageJob:'جارٍ تجهيز الصور', resume:'استكمال المتابعة', settings:'إعداد الخدمات', setupHelp:'على السيرفر، انسخ .env.example إلى .env وأضف مفاتيح OpenAI وElevenLabs ثم أعد التشغيل. لا تُرسل المفاتيح إلى المتصفح.', ready:'جاهز', savedHelp:'تُحفظ المشاريع تلقائيًا على السيرفر، ويحفظ المتصفح آخر مسودة أيضًا.',
};
const de = {
  workspace:'Video-Werkstatt', heading:'Eine Idee. Eine Geschichte. Dein Reel.', newProject:'Neues Projekt', projects:'Deine Projekte', chooseProject:'Gespeichertes Projekt öffnen', importPlan:'Plan importieren', exportPlan:'Plan herunterladen', deleteProject:'Projekt löschen', deleteConfirm:'Projekt löschen? Mediendateien bleiben erhalten.', idea:'Deine Videoidee', placeholder:'Beschreibe die Geschichte, das Publikum und deine Botschaft…', language:'Videosprache', duration:'Länge', style:'Stil', format:'Format', generate:'Mit KI erstellen', demoPlan:'Demoplan erstellen', seconds:'Sek.', vertical:'Hochformat', landscape:'Querformat', script:'Skript', scenes:'Szenen', voice:'Stimme', captions:'Untertitel', video:'MP4', images:'Bilder', empty:'Beginne mit deiner Idee', emptyText:'Plane die Geschichte, ergänze Bilder und Ton und lade dein Video herunter.', demoHelp:'Demokarten sowie eigene Bilder und Audiodateien funktionieren ohne API-Schlüssel.',
  saved:'Gespeichert', saving:'Wird gespeichert…', localDraft:'Lokaler Entwurf', retrySave:'Erneut speichern', connection:'Verbindung', connected:'Server verbunden', offline:'Server offline', check:'Verbindung prüfen', aiReady:'KI-Skript und Bilder bereit', aiDemo:'Demomodus · kein KI-Schlüssel', voiceReady:'ElevenLabs verbunden', voiceMissing:'ElevenLabs nicht eingerichtet', renderReady:'MP4-Export bereit', renderMissing:'FFmpeg fehlt', demoDraft:'Demoentwurf', aiDraft:'KI-Entwurf', manualDraft:'Dein Entwurf', name:'Projektname', scriptLabel:'Sprechertext', generateVoice:'Stimme erstellen', uploadAudio:'Audio hochladen', voiceId:'ElevenLabs-Stimmen-ID', loadVoices:'Meine Stimmen laden', voiceDefault:'Standardstimme', narration:'Sprecheraufnahme', downloadAudio:'Audio herunterladen', removeAudio:'Audio entfernen', voiceHelp:'Lade Audio hoch oder richte ElevenLabs auf dem Server ein.', audioFormats:'MP3, WAV, M4A, OGG, FLAC oder WebM · 20 MB · bis 3 Minuten',
  makeImages:'Bilder generieren', demoImages:'Demokarten erstellen', imageHelp:'Ein Bild pro Szene. Der Export fügt eine langsame Kamerabewegung hinzu.', prompt:'Bildbeschreibung', screenText:'Text im Bild', sceneTitle:'Szenentitel', uploadImage:'Bild hochladen', yourImage:'Dein Bild', aiImage:'KI-Bild', demoCard:'Demokarte', export:'Video exportieren', quality:'Videoqualität', preview:'720p · Vorschau', fullHD:'1080p · Full HD', burn:'Untertitel ins Video einbrennen', importSrt:'SRT hochladen', downloadSrt:'SRT herunterladen', removeSrt:'Importierte Untertitel entfernen', srtHelp:'ElevenLabs liefert synchronisierte Untertitel. Alternativ kannst du eine SRT-Datei hochladen.', noAudio:'Dieser Export enthält keine Sprecheraufnahme.', demoNotice:'Dieser Export enthält deutlich markierte Demokarten.', render:'MP4 exportieren', downloadVideo:'MP4 herunterladen', needImages:'Füge jeder Szene ein Bild hinzu, um zu exportieren.', optional:'optional', retry:'Erneut versuchen', planOnly:'JSON enthält Skript und Szenenplan. Mediendateien bleiben auf diesem Server.', creatingPlan:'Plan wird erstellt', generatingVoice:'Stimme wird erstellt', uploading:'Wird hochgeladen', rendering:'Video wird exportiert', imageJob:'Bilder werden vorbereitet', resume:'Auftrag weiter verfolgen', settings:'Einrichtung', setupHelp:'Kopiere .env.example nach .env, trage OpenAI- und ElevenLabs-Schlüssel ein und starte den Server neu. Schlüssel werden nie an den Browser gesendet.', ready:'Bereit', savedHelp:'Projekte werden automatisch auf dem Server gespeichert. Der Browser behält den letzten Entwurf.',
};
export function translator(locale) { const labels = { en, ar, de }[locale] || en; return key => labels[key] || en[key] || key; }
