const $=s=>document.querySelector(s);let project=null,approved=false,activeScene=0;
const langNames={de:'Deutsch',ar:'العربية',en:'English'};
function words(t){return t.trim().split(/\s+/).filter(Boolean)}
function generateScript(topic,lang,duration){const lines={de:[`Stell dir vor: ${topic}.`,`In den nächsten Sekunden zerlegen wir die Idee in klare Bilder – schnell, filmisch und ohne Leerlauf.`,`Erstens: Wir zeigen den stärksten visuellen Moment. Zweitens: Wir geben Kontext. Drittens: Wir bauen Spannung auf.`,`Am Ende bleibt eine klare Botschaft: ${topic} verdient einen Blick, der hängen bleibt.`],ar:[`تخيّل: ${topic}.`,`خلال الثواني القادمة نحول الفكرة إلى صور واضحة، بإيقاع سريع وأسلوب سينمائي.`,`أولاً نبدأ بأقوى لحظة بصرية. ثم نعطي السياق. وبعدها نبني التوتر وصولاً إلى الخلاصة.`,`وفي النهاية تبقى رسالة واحدة واضحة: ${topic}.`],en:[`Imagine this: ${topic}.`,`In the next few seconds, we turn the idea into clear images with fast, cinematic pacing.`,`First, show the strongest visual moment. Then add context. Next, build tension toward the payoff.`,`End on one clear message: ${topic}.`]}[lang];let base=lines.join('\n\n');if(duration>=45)base+='\n\n'+(lang==='ar'?'كل مشهد يجب أن يضيف معلومة أو إحساساً جديداً، من دون تكرار.':lang==='de'?'Jede Szene muss eine neue Information oder Emotion hinzufügen – ohne Wiederholung.':'Every scene must add a new piece of information or emotion without repetition.');return base}
function scenePrompts(topic,lang,duration){const n=duration>=60?6:duration>=45?5:4;const beats=['Hook / reveal','Context / environment','Detail / evidence','Tension / movement','Payoff / meaning','Closing image / CTA'];return Array.from({length:n},(_,i)=>({title:beats[i],start:Math.round(i*duration/n),end:Math.round((i+1)*duration/n),prompt:`Cinematic vertical 9:16 scene about “${topic}”. ${beats[i]}. Realistic lighting, documentary texture, deliberate camera movement, strong foreground/background separation, no text baked into image.`,caption:''}))}
function makeCaptions(script,duration){let w=words(script.replace(/\n+/g,' ')),per=Math.max(3,Math.ceil(w.length/Math.max(1,duration/2.4))),out=[];for(let i=0;i<w.length;i+=per){let idx=out.length,start=idx*duration/Math.ceil(w.length/per),end=(idx+1)*duration/Math.ceil(w.length/per);out.push({start,end,text:w.slice(i,i+per).join(' ')})}return out}
function srtTime(sec){let ms=Math.round(sec*1000),h=Math.floor(ms/3600000);ms%=3600000;let m=Math.floor(ms/60000);ms%=60000;let s=Math.floor(ms/1000),x=ms%1000;return [h,m,s].map(v=>String(v).padStart(2,'0')).join(':')+','+String(x).padStart(3,'0')}
function save(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function render(){document.body.dir=project?.lang==='ar'?'rtl':'ltr';$('#app').innerHTML=`<div class="shell"><aside class="side"><div class="logo">REEL <span>ENGINE AI</span></div><button onclick="newProject()">＋ New project</button><div class="nav">Projects<br>Templates<br>Assets<br>Integrations<br>Settings</div><small>v0.2 • local-first MVP</small></aside><main class="main"><div class="top"><div><div class="eyebrow">AI VIDEO WORKSPACE</div><h1>Idea → production plan → export.</h1></div><div class="badge">1080 × 1920 • 9:16</div></div>${!project?composer():workspace()}</main></div>`}
function composer(){return `<section class="composer"><textarea id="topic" placeholder="What should the reel be about?"></textarea><div class="row"><select id="lang"><option value="de">Deutsch</option><option value="ar">العربية</option><option value="en">English</option></select><select id="duration"><option value="30">30 sec</option><option value="45">45 sec</option><option value="60">60 sec</option></select><select id="style"><option>Cinematic documentary</option><option>Motion graphics</option><option>Educational</option><option>Fast social</option></select><button class="primary" onclick="createProject()">Generate production ✦</button></div><p class="notice">Runs locally without API keys. Provider integrations are optional and can be connected later.</p></section>`}
function workspace(){let rtl=project.lang==='ar'?'rtl':'';return `<div class="pipeline">${['Script','Scenes','Voice','Captions','Render','QA','Approval'].map((x,i)=>`<div class="stage ${i<6?'on':''}">${x}</div>`).join('')}</div><div class="grid"><div><section class="card"><h3>Script • ${langNames[project.lang]}</h3><textarea class="script ${rtl}" id="script" oninput="updateScript(this.value)">${project.script}</textarea><div class="tools"><button class="ghost" onclick="regenerate()">↻ Regenerate</button><button class="ghost" onclick="exportSRT()">Export SRT</button><button class="ghost" onclick="exportJSON()">Export project JSON</button></div></section><section class="card" style="margin-top:16px"><h3>Scene plan</h3>${project.scenes.map((s,i)=>`<div class="scene"><div class="num">${i+1}</div><div><b>${s.title}</b> <small>${s.start}s–${s.end}s</small><textarea onchange="editPrompt(${i},this.value)">${s.prompt}</textarea><button class="ghost" onclick="showScene(${i})">Preview scene</button></div></div>`).join('')}</section></div><div><section class="card"><h3>Vertical preview</h3><div class="preview"><div class="kicker">SCENE ${activeScene+1}</div><h2>${project.topic}</h2><p>${project.scenes[activeScene].title}</p><div class="caption">${project.captions[Math.min(activeScene,project.captions.length-1)]?.text||'Caption preview'}</div></div><div class="status"><div class="ok">✓ Script ready</div><div class="ok">✓ ${project.scenes.length} scenes</div><div class="ok">✓ ${project.captions.length} captions</div><div class="warn">○ Voice provider</div><div class="warn">○ Media provider</div><div class="ok">✓ Local QA</div></div></section><section class="card" style="margin-top:16px"><h3>Integrations</h3><p class="notice">Voice: ElevenLabs-ready adapter • Captions: Whisper-ready timing • Render: FFmpeg/Remotion-ready manifest. No secret keys are stored in this demo.</p><div class="tools"><button class="ghost" onclick="downloadManifest()">Download render manifest</button><button class="ghost" onclick="runQA()">Run QA</button></div></section></div></div><div class="approval"><span>${approved?'✓ Draft approved for rendering/export':'Human approval required before final render/publishing'}</span><button class="primary" onclick="approve()">${approved?'Approved':'Approve draft'}</button></div>`}
function createProject(){let topic=$('#topic').value.trim();if(!topic)return alert('Enter a topic first.');let lang=$('#lang').value,duration=+$ ('#duration').value;project={id:Date.now(),topic,lang,duration,style:$('#style').value,script:generateScript(topic,lang,duration),scenes:scenePrompts(topic,lang,duration)};project.captions=makeCaptions(project.script,duration);activeScene=0;approved=false;localStorage.setItem('reel-engine-project',JSON.stringify(project));render()}
function newProject(){project=null;approved=false;document.body.dir='ltr';render()}
function updateScript(v){project.script=v;project.captions=makeCaptions(v,project.duration);persist()}
function editPrompt(i,v){project.scenes[i].prompt=v;persist()}
function persist(){localStorage.setItem('reel-engine-project',JSON.stringify(project))}
function regenerate(){project.script=generateScript(project.topic,project.lang,project.duration);project.scenes=scenePrompts(project.topic,project.lang,project.duration);project.captions=makeCaptions(project.script,project.duration);approved=false;persist();render()}
function showScene(i){activeScene=i;render()}
function approve(){approved=true;render()}
function exportSRT(){let s=project.captions.map((c,i)=>`${i+1}\n${srtTime(c.start)} --> ${srtTime(c.end)}\n${c.text}\n`).join('\n');save(`${slug(project.topic)}.srt`,s)}
function exportJSON(){save(`${slug(project.topic)}.json`,JSON.stringify(project,null,2),'application/json')}
function downloadManifest(){let m={version:'0.2',canvas:{width:1080,height:1920,fps:30},duration:project.duration,voice:{provider:'elevenlabs',status:'not-configured'},captions:{provider:'whisper-compatible',items:project.captions},scenes:project.scenes,script:project.script,approval:approved};save(`${slug(project.topic)}-render-manifest.json`,JSON.stringify(m,null,2),'application/json')}
function runQA(){let issues=[];if(words(project.script).length<20)issues.push('Script is very short');if(project.scenes.some(s=>!s.prompt.trim()))issues.push('A scene has no visual prompt');if(project.captions.some(c=>c.text.length>120))issues.push('Some captions are too long');alert(issues.length?'QA warnings:\n• '+issues.join('\n• '):'QA passed: script, scenes and caption structure look valid.')}
function slug(x){return x.toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/gi,'-').replace(/^-|-$/g,'').slice(0,50)||'reel-project'}
let cached=localStorage.getItem('reel-engine-project');if(cached){try{project=JSON.parse(cached)}catch{}}render();
