import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Film,Mic,Subtitles,Play,CheckCircle2,Sparkles}from'lucide-react';
import'./style.css';
const stages=[['Script',Sparkles],['Scenes',Film],['Voice',Mic],['Captions',Subtitles],['Render',Play],['QA',CheckCircle2]];
const API=import.meta.env.VITE_API_URL||'http://localhost:8787';
function App(){
 const[topic,setTopic]=useState('');const[lang,setLang]=useState('de');const[duration,setDuration]=useState(30);const[style,setStyle]=useState('Cinematic documentary');const[project,setProject]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const scenes=useMemo(()=>project?.scenes||[],[project]);
 async function generate(){if(!topic.trim())return;setLoading(true);setError('');try{const r=await fetch(`${API}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,language:lang,duration,style})});const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error||'Generation failed');setProject({topic,lang,duration,style,...data});}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <main><aside><h2>REEL <span>ENGINE AI</span></h2><p>v0.4</p><nav>Projects<br/>Assets<br/>Providers<br/>Settings</nav></aside><section><header><div><small>AI VIDEO WORKSPACE</small><h1>Idea → Reel pipeline</h1></div><b>1080 × 1920</b></header><div className="composer"><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What should the video be about?"/><div className="row"><select value={lang} onChange={e=>setLang(e.target.value)}><option value="de">Deutsch</option><option value="ar">العربية</option><option value="en">English</option></select><select value={duration} onChange={e=>setDuration(+e.target.value)}><option value="30">30 sec</option><option value="45">45 sec</option><option value="60">60 sec</option></select><select value={style} onChange={e=>setStyle(e.target.value)}><option>Cinematic documentary</option><option>Motion graphics</option><option>Educational</option><option>Fast social</option></select><button disabled={loading} onClick={generate}>{loading?'Generating…':'Generate with AI ✦'}</button></div>{error&&<p className="error">{error}</p>}</div><div className="pipeline">{stages.map(([x,I])=><div key={x}><I size={18}/>{x}</div>)}</div>{project&&<div className="grid"><article><h3>Script {project.mode==='ai'?'• AI':'• Demo'}</h3><textarea className="script" dir={lang==='ar'?'rtl':'ltr'} value={project.script} onChange={e=>setProject({...project,script:e.target.value})}/><h3>Scenes</h3>{scenes.map((s,i)=><div className="scene" key={i}><b>{i+1}</b><div><strong>{s.title} · {s.start}s–{s.end}s</strong>{s.voiceover&&<p><em>Voice:</em> {s.voiceover}</p>}<p>{s.visualPrompt||s.prompt}</p>{s.onScreenText&&<small>Text: {s.onScreenText}</small>}</div></div>)}</article><article><h3>Production status</h3><p>✓ AI script & scene director</p><p>○ ElevenLabs voice</p><p>○ Whisper captions</p><p>○ Media generation</p><p>○ FFmpeg render</p><div className="preview"><small>VERTICAL PREVIEW</small><h2>{project.topic}</h2><p>{scenes[0]?.title}</p></div>{project.warning&&<p className="error">{project.warning}</p>}</article></div>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);
